services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/airbnb_backend/
    ports:
     - 8000:8000
    env_file:
     - ./.env.dev
    depends_on:
     - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgressql/data
    environment:
     - POSTGRES_USER=postgresuser
     - POSTGRES_PASSWORD=postgrespassword
     - POSTGRES_DB=airbnb-db
volumes:
  postgres_data:

